### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by mzszym** [Kucoin/kumex-python-sdk#5]
I cannot get your first example to run. I tried installing your module in a clean venv:

```bash
python -m venv ~/kumex-test
source ~/kumex-test/bin/activate
pip install python-kumex==1.0.8
```

and then executing first lines of your example in Python

```python
>>> from kumex.client import Market
>>> client = Market()
>>> l3_depth = client.l3_order_book('XBTUSDM')
```

This gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marek/kumex-test/lib/python3.7/site-packages/kumex/marke_data/market_data.py", line 311, in l3_order_book
    return self._request('GET', '/api/v1/level3/snapshot', auth=False, params=params)
  File "/Users/marek/kumex-test/lib/python3.7/site-packages/kumex/base_request/base_request.py", line 65, in _request
    return self.check_response_data(response_data)
  File "/Users/marek/kumex-test/lib/python3.7/site-packages/kumex/base_request/base_request.py", line 84, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 403-<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 4VTZL_QYw3szF-1nHBWM_01U49tYx3M-6-YvmowjMj9OyhomWUFrUQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by grape-cola** [comment]
Repaired，

**Comment by grape-cola** [comment]
Repaired， use v1.0.10
